spring.application.name=ananta

# Database placeholders (Render will provide these)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate

# Security placeholders
SECRET_KEY=${JWT_SECRET}
RAZORPAY_API_KEY=${RAZOR_KEY}
RAZORPAY_API_SECRET=${RAZOR_SECRET}

# Email placeholders
spring.mail.username=${EMAIL_USER}
spring.mail.password=${EMAIL_PASS}
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

WEB_NAME=https://ananta-ecomm.onrender.com
