spring.application.name=ananta

spring.datasource.url={DATABASE  url}
spring.datasource.username={$DB Password}
spring.datasource.password={$DB Password}

server.servlet.context-path=/ananta/v1

SECRET_KEY = {JWT_SECRET_KEY}