spring.application.name=ananta

spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_db
spring.datasource.username=springstudent
spring.datasource.password=springstudent

server.servlet.context-path=/ananta/v1

SECRET_KEY = "MoohVy7HQeQRVVQjbu6HfO0MFPAFWorkC+NQ1yHkOSE="

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=myworkbench1@gmail.com
spring.mail.password=nmia hepe zxjs mnjn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true