spring.application.name=ananta

# This tells Spring to use 'dev' unless an environment variable says otherwise
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

server.servlet.context-path=/ananta/v1

# Common Multipart settings
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Common JPA settings
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.type.descriptor.sql.BinaryTypeDescriptor=REPEATABLE_READ

server.port=${PORT:8080}

spring.jpa.defer-datasource-initialization=true

# for unnecessary hitting of Neon Db by hikari pool
spring.datasource.hikari.minimum-idle=0
spring.datasource.hikari.idle-timeout=60000
spring.datasource.hikari.max-lifetime=120000
