spring.application.name=ananta

# This tells Spring to use 'dev' unless an environment variable says otherwise
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

server.servlet.context-path=/ananta/v1

# Common Multipart settings
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=1MB
spring.servlet.multipart.max-request-size=1MB

# Common JPA settings
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.type.descriptor.sql.BinaryTypeDescriptor=REPEATABLE_READ
